{% set version = '2.8.6' %}
{% set versionu = '2_8_6' %}
{% set posix = 'm2-' if win else '' %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{version}}

source:
  fn: rpy2-{{version}}.tar.gz
  url: https://pypi.io/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: 004d13734a7b9a85cbc1e7a93ec87df741e28db1273ab5b0d9efaac04a9c5f98
  # Regenerate the patches using the following command:
  # mercurial_program export -r 3066:3072 -o 000%n-%m.patch -g
  patches:
    # Patches to be upstreamed:
    - 0001-ResetConsole_is_not_a_member_of_structRstart.patch
    - 0002-Win32__Add_missing_jump_to_toplevel___extern.patch
    - 0003-Win32__Fix_incorrect_type_of__buf__parameter_to_EmbeddedR_ReadConsole__.patch
    - 0004-Win32__Add_missing__include__stdlib_h_.patch
    - 0005-Win32__Hack_sysconfig_so_that__CC__is_set_to__gcc_.patch
    - 0006-Win32__Add___MINGW_USE_ANSI_STDIO_1_and__Wno-format_for___zd__in__rinterface_c.patch
    - 0007-Turn_off_some_pedantic_warnings__unused_variables_and_functions_.patch
    - 0008-Win32__Change_R_USER_check_for_HOMEDIR_to_HOMEDRIVE.patch
    - 0009-Win32__Use_get_R_HOME___if_R_HOME_is_not_set_.patch
    - 0010-Win32__Elide-include-R_ext_eventloop_h.patch
    - 0011-Do-not-assume-numpy-float128-exists.patch
    # Patches from upstream:
    - 0110-52b73245e093d4cf32dfeb7c77e9f4da954316dc.patch
    - 0111-c090410d52149121083ce87387c93ea91514c39f.patch

build:
  merge_build_host: True  # [win]
  number: 2
  skip: True  # [not py2k]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    # Note, until the build env. is activated properly, you'll need posix in your
    # root env. too. Proper activation is in-progress though.
    - posix                # [win]
    - {{pfx}}toolchain     # [win]
    - {{posix}}patch
    - {{posix}}git

  host:
    - python
    - setuptools
    - r-base
    - singledispatch       # [not (py>=34)]
    - six
    - readline             # [not win]
  run:
    - python
    - r-base
    - singledispatch       # [not (py>=34)]
    - six
    - readline             # [not win]
    - {{pfx}}gcc-libs      # [win]

test:
  requires:
    - r-survival
    - r-ggplot2
    - r-dplyr
    - ipython
    - numpy
    - pandas
    - mock
  imports:
    - rpy2
    - rpy2.interactive        # [not win]
    - rpy2.interactive.tests  # [not win]
    - rpy2.ipython            # [not win]
    - rpy2.ipython.tests      # [not win]
    - rpy2.rinterface         # [not win]
    - rpy2.rinterface.tests   # [not win]
    - rpy2.rlike              # [not win]
    - rpy2.rlike.tests        # [not win]
    - rpy2.robjects           # [not win]
    - rpy2.robjects.lib       # [not win]
    - rpy2.robjects.lib.tests  # [not win]
    - rpy2.robjects.tests     # [not win]
  commands:
    - python -m rpy2.tests    # [not win]

about:
  home: http://rpy.sourceforge.net
  license: GPL-2.0
  summary: 'Python interface to the R language (embedded R)'

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
