{% set version = "3.0.4" %}
{% set ver = version|replace(".", "_") %}

package:
  name: rpy2
  version: {{version}}

source:
  url: https://bitbucket.org/rpy2/rpy2/get/RELEASE_{{ ver }}.tar.gz
  sha256: fc649bd25d06febd3db382ac3e77b4945fa9b8843a664b86d7c27c06fc912f19

build:
  number: 0
  merge_build_host: True  # [win]

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - pip
    - cffi >=1.0.0
  run:
    - r-base
    - python
    - jinja2
    - tzlocal
    - cffi >=1.0.0

test:
  source_files:
    - tests
  requires:
    - r-survival
    - ipython
    - pandas
    - pytest
  imports:
    - rpy2
    # - rpy2.interactive
    - rpy2.ipython
    - rpy2.rinterface
    - rpy2.rlike
    - rpy2.robjects
    - rpy2.robjects.lib
  commands:
    - pytest tests

about:
  home: http://rpy.sourceforge.net
  license: GPL-2.0
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: 'Python interface to the R language (embedded R)'

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
