{% set name = "rpy2" %}
{% set version = "3.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: rpy2
  version: {{ version }}

source:
  # the tag on github has the format RELEASE_x_x_x
  url: https://github.com/rpy2/rpy2/archive/refs/tags/RELEASE_{{ version.replace('.', '_') }}.tar.gz
  sha256: 241411d196e08f571c72904647018ef242df11ed5cd6c1fdcfcabf3e6ecbc645

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - liblzma-devel                       # [build_platform != target_platform]
    - zlib                                # [build_platform != target_platform]
    - libdeflate                          # [build_platform != target_platform]
    - {{ posix }}make
    - {{ posix }}base                     # [win]
  host:
    - python
    - pip
    - setuptools >=61
    - jinja2
    - tzlocal
    - r-base
    - cffi >=1.15.1
    - liblzma-devel                       # [not win]
    - libdeflate                          # [not win]
    - zlib                                # [not win]
  run:
    - python
    - jinja2
    - tzlocal
    - r-base
    - cffi >=1.15.1
    - packaging

test:
  source_files:
    - ./
  requires:
    - r-cairo  # [not win]
    - r-ggplot2 >=2.2.1
    - r-survival
    - ipython
    - numpy
    - pandas
    - pytest
    - {{ posix }}make  # [win]
  commands:
    - pytest -s -rxs -v rpy2-rinterface/
    - pytest -s -rxs -v rpy2-robjects/ -k "not test_svg_plotting_args and not test_POSIXct_datetime_from_timestamp"  # [not win]

about:
  home: https://github.com/rpy2/rpy2
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: Python interface to the R language (embedded R)
  doc_url: https://rpy2.github.io/

extra:
  recipe-maintainers:
    - conda-forge/r
    - ceholden
    - ocefpaf
