{% set version = '2.9.4' %}
{% set versionu = '2_9_4' %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{version}}

source:
  fn: rpy2-{{version}}.tar.gz
  url: https://pypi.io/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: be57f741d0c284b5d8785ab03dff0e829303e5ac30e548d5ceb46e05b168812e
  # Regenerate the patches using the following command:
  # mercurial_program export -r 3066:3072 -o 000%n-%m.patch -g
  patches:
    # Patches to be upstreamed:
    - 0001-ResetConsole_is_not_a_member_of_structRstart.patch
    - 0002-Win32__Add_missing_jump_to_toplevel___extern.patch
    - 0003-Win32__Fix_incorrect_type_of__buf__parameter_to_EmbeddedR_ReadConsole__.patch
    - 0004-Win32__Add_missing__include__stdlib_h_.patch
    - 0005-Win32__Hack_sysconfig_so_that__CC__is_set_to__gcc_.patch
    - 0006-Win32__Add___MINGW_USE_ANSI_STDIO_1_and__Wno-format_for___zd__in__rinterface_c.patch
    - 0007-Turn_off_some_pedantic_warnings__unused_variables_and_functions_.patch
    - 0008-Win32__Change_R_USER_check_for_HOMEDIR_to_HOMEDRIVE.patch
    - 0009-Win32__Use_get_R_HOME___if_R_HOME_is_not_set_.patch
    - 0010-Win32__Elide-include-R_ext_eventloop_h.patch
    - 0011-Disable-broken-numpy-test.patch

build:
  merge_build_host: True  # [win]
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('fortran') }}  # [linux]
    # Note, until the build env. is activated properly, you'll need posix in your
    # root env. too. Proper activation is in-progress though.
    - posix                # [win]
    - {{pfx}}toolchain     # [win]
  host:
    - {{ compiler('c') }}  # [not win]
    - git
    - python
    - setuptools
    - r-base
    - singledispatch       # [not (py>=34)]
    - six
    - jinja2
    - readline             # [linux]
    - bzip2                # [linux]
  run:
    - {{ compiler('c') }}  # [not win]
    - python
    - r-base
    - r-rsqlite
    - r-dbplyr
    - singledispatch       # [not (py>=34)]
    - six
    - jinja2
    - {{pfx}}gcc-libs      # [win]

test:
  requires:
    - r-survival
    - r-ggplot2 >=3.0.0
    - r-dplyr
    - ipython
    - simplegeneric
    - numpy
    - pandas
    - mock
    - tzlocal
  imports:
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests
  commands:
    - python -m rpy2.tests           # [not linux]
    # The tests run ok, but python segfaults at exit
    # - xvfb-run python -m rpy2.tests  # [linux]

about:
  home: http://rpy.sourceforge.net
  license: GPL2
  license_family: GPL2
  summary: 'Python interface to the R language (embedded R)'

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
