{% set version = "3.3.2" %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: 2e12c99e56a1faa68f3b82a71b90e3389203c1e76cd53fe38946a8a7a31f9750
  patches:
    - 0001-Fix-multiprocessing-test.patch

build:
  number: 1
  merge_build_host: true  # [win]
  skip: true  # [py2k or r_base=="3.5.1"]

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - pip
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,!=1.13.0
  run:
    - python
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,!=1.13.0

test:
  source_files:
    - rpy2/tests
  requires:
    - r-cairo  # [not (aarch64 or ppc64le)]
    - r-survival
    - r-ggplot2 >=2.2.1
    - ipython
    - numpy
    - pandas
    - pytest
  imports:
    - rpy2
    - rpy2.rlike
    # calls `get_rlib_path` an that only works for *nix
    - rpy2.ipython  # [not win]
    - rpy2.rinterface  # [not win]
    - rpy2.robjects  # [not win]
    - rpy2.robjects.lib  # [not win]
  commands:
    - pytest -s -rxs -v rpy2/tests -k "not test_display_args and not test_svg_plotting_args"  # [not (win or aarch64 or ppc64le)]
    - pytest -s -rxs -v rpy2/tests --ignore=rpy2/tests/ipython --ignore rpy2/tests/robjects/lib/test_ggplot2.py --ignore rpy2/tests/robjects/lib/test_grdevices.py --ignore rpy2/tests/robjects/lib/test_grid.py  # [aarch64 or ppc64le]

about:
  home: https://rpy2.bitbucket.io/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: Python interface to the R language (embedded R)

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
