{% set version = "3.5.16" %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: 837e2f74583658a5c4c339761a73f9434f33ef9ced3e30c64da7562165c2801b

build:
  number: 4

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
    - m2-base                               # [win]
    - {{ compiler('c') }}                 # [not win]
    - {{ stdlib("c") }}                   # [not win]
    - {{ compiler('m2w64_c') }}           # [win]
    - {{ stdlib("m2w64_c") }}             # [win]
    - make
  host:
    - python
    - setuptools
    - libpython  # [win]
    - pip
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.10.0,!=1.13.0
  run:
    - python
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - packaging  # [win]
    - cffi >=1.10.0,!=1.13.0

test:
  source_files:
    - rpy2/tests
  requires:
    - r-cairo  # [not (win or aarch64 or ppc64le)]
    - r-dplyr
    - r-dbplyr
    - r-ggplot2 >=2.2.1
    - r-lazyeval
    - r-survival
    - ipython
    - numpy
    - pandas
    - pytest
  imports:
    - rpy2
    - rpy2.rlike
    # calls `get_rlib_path` an that only works for *nix
    - rpy2.ipython       # [not win]
    - rpy2.rinterface    # [not win]
    - rpy2.robjects      # [not win]
    - rpy2.robjects.lib  # [not win]
  commands:
    - pytest -s -rxs -v rpy2/tests -k "not test_display_args and not test_svg_plotting_args and not test_POSIXct_datetime_from_timestamp"  # [not (win or aarch64 or ppc64le)]
    - pytest -s -rxs -v rpy2/tests --ignore=rpy2/tests/ipython --ignore rpy2/tests/robjects/lib/test_ggplot2.py --ignore rpy2/tests/robjects/lib/test_grdevices.py --ignore rpy2/tests/robjects/lib/test_grid.py -k "not test_POSIXct_datetime_from_timestamp"  # [win or aarch64 or ppc64le]

about:
  home: https://github.com/rpy2/rpy2
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: Python interface to the R language (embedded R)
  doc_url: https://rpy2.github.io/

extra:
  recipe-maintainers:
    - conda-forge/r
    - ceholden
    - ocefpaf
