{% set version = "3.5.0" %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: 4d8a20253320ae3e402ec20d56640772bdc27731bd14f7d0475a95d86e7cd1c7

build:
  number: 0
  skip: true  # [r_base == "3.6" and osx and arm64]
  merge_build_host: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make
  host:
    - python
    - libpython  # [win]
    - pip
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,!=1.13.0
  run:
    - python
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,!=1.13.0

test:
  source_files:
    - rpy2/tests
  requires:
    - r-cairo  # [not (aarch64 or ppc64le)]
    - r-survival
    - r-ggplot2 >=2.2.1
    - ipython
    - numpy
    - pandas
    - pytest
  imports:
    - rpy2
    - rpy2.rlike
    # calls `get_rlib_path` an that only works for *nix
    - rpy2.ipython  # [not win]
    - rpy2.rinterface  # [not win]
    - rpy2.robjects  # [not win]
    - rpy2.robjects.lib  # [not win]
  commands:
    - pytest -s -rxs -v rpy2/tests -k "not test_display_args and not test_svg_plotting_args"  # [not (win or aarch64 or ppc64le)]
    - pytest -s -rxs -v rpy2/tests --ignore=rpy2/tests/ipython --ignore rpy2/tests/robjects/lib/test_ggplot2.py --ignore rpy2/tests/robjects/lib/test_grdevices.py --ignore rpy2/tests/robjects/lib/test_grid.py  # [aarch64 or ppc64le]

about:
  home: https://github.com/rpy2/rpy2
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: Python interface to the R language (embedded R)
  doc_url: https://rpy2.github.io/

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
    - dbast
