{% set version = "3.0.5" %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{version}}

source:
  url: https://pypi.io/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: c1fcd966780ebc3ea2400f73b558a801fbc17c09312f55d27b391b48fc24c8f9
  patches:
    # patches to be upstreamed:
    - 0001-ResetConsole_is_not_a_member_of_structRstart.patch
    - 0002-Win32__Add_missing_jump_to_toplevel___extern.patch
    - 0003-Win32__Fix_incorrect_type_of__buf__parameter_to_EmbeddedR_ReadConsole__.patch
    - 0004-Win32__Add_missing__include__stdlib_h_.patch
    - 0005-Win32__Hack_sysconfig_so_that__CC__is_set_to__gcc_.patch
    - 0006-Win32__Add___MINGW_USE_ANSI_STDIO_1_and__Wno-format_for___zd__in__rinterface_c.patch
    - 0007-Turn_off_some_pedantic_warnings__unused_variables_and_functions_.patch
    - 0008-Win32__Change_R_USER_check_for_HOMEDIR_to_HOMEDRIVE.patch
    - 0009-Win32__Use_get_R_HOME___if_R_HOME_is_not_set_.patch
    - 0010-Win32__Elide-include-R_ext_eventloop_h.patch
    - 0011-fix_capture_R_config_flags.patch

build:
  merge_build_host: True  # [win]
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - pip
    - r-base
    - singledispatch  # [not (py>=34)]
    - six
    - jinja2
    - readline      # [not win]
    - simplegeneric
  run:
    - python
    - r-base
    - r-rsqlite
    - r-dbplyr
    - singledispatch  # [not (py>=34)]
    - six
    - jinja2
    - readline      # [not win]
    - tzlocal
    - simplegeneric

test:
  requires:
    - r-survival
    - r-ggplot2 2.2.1
    - r-dplyr
    - ipython
    - numpy
    - pandas
    - mock
  imports:
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.ipython
    - rpy2.ipython.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests
  commands:
    - "python -m rpy2.tests > test_run.txt 2>&1 || true"  # [not win]
    - cat test_run.txt                                    # [not win]
    # Expect 4 failures due to https://github.com/numpy/numpy/issues/11150
    - cat test_run.txt | grep "errors=4"                  # [not win]

about:
  home: http://rpy.sourceforge.net
  license: GPL-2.0
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: 'Python interface to the R language (embedded R)'

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
