{% set version = "3.1.0" %}
{% set pfx = 'm2w64-' if win else '' %}

package:
  name: rpy2
  version: {{version}}

source:
  url: https://pypi.io/packages/source/r/rpy2/rpy2-{{ version }}.tar.gz
  sha256: ed4284df32d00b1fba5b1409e5df64b04b02d47aff543d6ef1dc211ab94e247f

build:
  number: 0
  merge_build_host: True  # [win]
  skip: True  # [py2k]

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - pip
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,<1.13.0a0
  run:
    - python
    - r-base
    - jinja2
    - pytz
    - simplegeneric
    - tzlocal
    - cffi >=1.0.0,<1.13.0a0

test:
  source_files:
    - rpy/tests
  requires:
    - r-survival
    - r-ggplot2 >=2.2.1
    - ipython
    - numpy
    - pandas
    - pytest
  imports:
    - rpy2
    - rpy2.rlike
    # calls `get_rlib_path` an that only works for *nix
    - rpy2.ipython  # [not win]
    - rpy2.rinterface  # [not win]
    - rpy2.robjects  # [not win]
    - rpy2.robjects.lib  # [not win]
  commands:
    - pytest -s -rxs -v rpy/tests  # [not win]

about:
  home: https://rpy2.bitbucket.io/
  license: GPL-2.0
  license_family: GPL
  license_file: gpl-2.0.txt
  summary: "Python interface to the R language (embedded R)"

extra:
  recipe-maintainers:
    - bgruening
    - ceholden
    - johanneskoester
    - mingwandroid
    - ocefpaf
