# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6r_base3.4.1
    - CONFIG=osx_python3.6r_base3.5.1
    - CONFIG=osx_python3.7r_base3.4.1
    - CONFIG=osx_python3.7r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GbiryjRadWLiJb4Rw3wn+LG13H69QORNm6YyrBHTQ6DhHjhJ0agh/drfon9PV/c4vWY7A1MzLJSs+WWnOfwwEZWIIgm39ui0NLQQvLUNc3UzKElpe1mEIeQ06rUEYpcxub8wHkBB2fySbcrYwASKoPKsttgQdzJh6kxVHbDwr/nfD+zL/QI6VGl4JUTUDQiYf11eDDFxtunoyuGO2rqWW/8NmNgHTgk4QXkDmC0kTfletyxsdQkEDk4uXtNVnyDQ0R79Hx2TzOYuICbAN8gw0ll4tE0++77IeXTQ94778dY3JdvjVn2AKsx/ylqoHDxStE0x1OoFGi+qrDH0FvegZP+rMJ3FPTLj2KgAbcnz+gjk3UMfKeG4XFfbLThPRhtRautgGq8KjysnbORwBC3F6sWUoaE+sDTyuYo2650ZksQwI6ho/RFeXb+jOHfU5NhScXSdNDXeHJ10VXZ06O4Gl8LHQNnc1BQwgq2MjRX0ReV5zLtexXlH3E6/e2x2T32J4jB4Oa3Q762bgSQEiqEak4AeY8bJLV8UvxNR04sj7GfFOF/QvCTWUmc8quOElNxC3L5Lk3TZV4QGjfzvbEJsZBV4DHSZO1WVZbD8zcA8Ej8mPIJsa70QuOQNgIavhEglXmBXVCStyJWKkydU/y84ixjtxS83eK2z4rIAWaakZFU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
