version: 2

jobs:
  build__CONDA_PY_27__CONDA_R_3.3.2:
    working_directory: ~/test
    machine: true
    environment:
      - CONDA_PY: "27"
      - CONDA_R: "3.3.2"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CONDA_PY=${CONDA_PY}"
            echo "CONDA_R=${CONDA_R}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__CONDA_PY_27__CONDA_R_3.4.1:
    working_directory: ~/test
    machine: true
    environment:
      - CONDA_PY: "27"
      - CONDA_R: "3.4.1"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CONDA_PY=${CONDA_PY}"
            echo "CONDA_R=${CONDA_R}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__CONDA_PY_35__CONDA_R_3.3.2:
    working_directory: ~/test
    machine: true
    environment:
      - CONDA_PY: "35"
      - CONDA_R: "3.3.2"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CONDA_PY=${CONDA_PY}"
            echo "CONDA_R=${CONDA_R}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__CONDA_PY_35__CONDA_R_3.4.1:
    working_directory: ~/test
    machine: true
    environment:
      - CONDA_PY: "35"
      - CONDA_R: "3.4.1"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CONDA_PY=${CONDA_PY}"
            echo "CONDA_R=${CONDA_R}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__CONDA_PY_36__CONDA_R_3.3.2:
    working_directory: ~/test
    machine: true
    environment:
      - CONDA_PY: "36"
      - CONDA_R: "3.3.2"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CONDA_PY=${CONDA_PY}"
            echo "CONDA_R=${CONDA_R}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__CONDA_PY_36__CONDA_R_3.4.1:
    working_directory: ~/test
    machine: true
    environment:
      - CONDA_PY: "36"
      - CONDA_R: "3.4.1"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CONDA_PY=${CONDA_PY}"
            echo "CONDA_R=${CONDA_R}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build__CONDA_PY_27__CONDA_R_3.3.2
      - build__CONDA_PY_27__CONDA_R_3.4.1
      - build__CONDA_PY_35__CONDA_R_3.3.2
      - build__CONDA_PY_35__CONDA_R_3.4.1
      - build__CONDA_PY_36__CONDA_R_3.3.2
      - build__CONDA_PY_36__CONDA_R_3.4.1
